version: 2

jobs:
  build:
    docker:
      - image: docker:17.12.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t fatwhaleltd/tectonicdb .
      - run: docker create --name tectonicdb fatwhaleltd/tectonicdb
      - run: docker cp tectonicdb:/usr/local/bin/tectonic-server /tmp/tectonic-server
      - store_artifacts:
          path: /tmp/tectonic-server
          destination: tectonic-server
      - run: |
          docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD
          docker push fatwhaleltd/tectonicdb:latest

  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install curl file build-essential pkg-config libssl-dev -y
      - restore_cache:
          key: v2-cargo-nightly-2017-01-30-{{ arch }}
          paths:
            - ~/.cargo
      - run: |
          test -f ~/.cargo/bin/cargo || (curl https://sh.rustup.rs -s > /home/install.sh &&
          chmod +x /home/install.sh &&
          sh /home/install.sh -y --verbose --default-toolchain nightly-2018-01-30)
      - save_cache:
          key: v2-cargo-nightly-2017-01-30-{{ arch }}
          paths:
            - ~/.cargo
      - restore_cache:
          key: v1-tectonicdb-test-{{ arch }}
          paths:
            - ~/project/target/
      - run: |
          ~/.cargo/bin/rustup default nightly-2018-01-30 && \
          ~/.cargo/bin/cargo test --no-fail-fast -- --nocapture
      - save_cache:
          key: v1-tectonicdb-test-{{ arch }}
          paths:
            - ~/project/target/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test
